### ISSUE TITLE
Parallel execution of Scorer

### ISSUE THREAD

**Issue by felixkluge** [mad-lab-fau/tpcp#76]
For scoring an algorithm on a large Dataset, I would like to run the Scorer using parallel execution. 

While I see this option for tpcp.validate.cross_validate (n_jobs), it is not available for tpcp.validate.Scorer.

What would be the best way going forward? Using cross_validate with a leave one out CV, although that adds some overhead (definition of the cross validation)?

**Comment by AKuederle** [comment]
Good point! I was thinking about this as well yesterday.

At the moment this is not possible.
Also using the n_jobs argument of `cross_validate` will not do what you might think. This will run each fold in one job not the execution of each datapoint.

I think the scorer could be changed relativly easily to support parallel execution as well.
The only part I am not sure about is the `single_scorer_callback`. This needs to be called in the main thread.

However, using the new `joblib>0.13` generator feature that should be possible. I will try that out in the next couple of days.

**Comment by AKuederle** [comment]
A first implementation was introduced with #95

**Comment by AKuederle** [comment]
@felixkluge could you test that feature for your usecase before I make a release? Is this what you expect and does it provide the performance increase you expect?

**Comment by felixkluge** [comment]
@AKuederle it seems to successfully score/analyse data points in parallel according to the n_jobs parameter of the Scorer class. Also the speed up is reasonable (I did not do any benchmarking though).

**Comment by AKuederle** [comment]
@felixkluge There is now also a `validate` function #99.

0.25.0 was just released including these changes. Please note that we dropped py3.8 support in this release

**Comment by felixkluge** [comment]
@AKuederle What would be the advantage of using `validate` over `Scorer` directly?

**Comment by AKuederle** [comment]
Validate provides an interface and output that is identical to cross_validate. In particular that includes formatting of the output. Internally `validate` just call Scorer with the appropriate arguments.

**Comment by felixkluge** [comment]
Thanks!
