### ISSUE TITLE
Caching experiences

### ISSUE THREAD

**Issue by fleiscse** [mad-lab-fau/tpcp#91]
This was my experience / initial understanding of the caching functionality. 

I was unsure if I might need this functionality for the amount of data I want to load, but it seemed like a nice concept to me. I am not sure what is considered "time-consuming", but when I was loading data some time ago (for a diferent project) it always took aounrd half a minute / minute to load, which was already a bit annoying. 

From the example on the tpcp page I understood that the lru_cache function is called when I call the .data property, which then calls the load_pandas_pickle_file function. However, I thought that this function just reads the value / data from the cache. I thought that for retrieving data from the cache the values need to be stored there first, and I did not understand how this happens. Also I did not get what the number (10) means, but I also did not really think about this, I would have just used this value.

What I also did not know is that only a certain number of executions are stored in the cache. I thought that once it is there, it just "stays there", unless it is somehow overwritten. 

Hope this helps :)

**Comment by AKuederle** [comment]
Full example is now available here: https://tpcp.readthedocs.io/en/latest/auto_examples/recipies/_01_caching.html#sphx-glr-auto-examples-recipies-01-caching-py
