### ISSUE TITLE
Snapshot testing util does not work with datatime index

### ISSUE THREAD

**Issue by AKuederle** [mad-lab-fau/tpcp#92]
When trying to save a pandas df with a datetime index with the snapshot test, the roundtrip does not work, as pandas seems to round the timestamps before saving.

A workaround is to round the timestamps to ms before applying the snapshot, but we should just directly integrate this workaround in the testing tools

**Comment by AKuederle** [comment]
Had to reopen the issue, as I am still having trouble with that for some ns-timestamps. Will investigate further.
For now old workaround is still valid

**Comment by a-mosquito** [comment]
Maybe this is related to [this issue](https://github.com/pandas-dev/pandas/issues/53473)?

**Comment by AKuederle** [comment]
Actually fixed by #112
